---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.1"
    name: elastic 
  - src: git@github.com:mgesler/kibana-role.git
    scm: git
    version: "1.0.2"
    name: kibana
  - src: git@github.com:mgesler/filebeat-role.git
    scm: git
    version: "1.0.1"
    name: filebeat  
