---
- name: Install Elasticsearch
  hosts: elasticsearch
  handlers:
    - name: restart Elasticsearch
      become: true
      ansible.builtin.service:
        name: elasticsearch
        state: restarted
  tasks:
    - name: "Download Elasticsearch's rpm"
      ansible.builtin.get_url:
        url: "http://10.2.25.120/elasticsearch-{{ version }}-x86_64.rpm"
        dest: "/tmp/elasticsearch-{{ version }}-x86_64.rpm"
        mode: 0755
      register: download_elastic
      until: download_elastic is succeeded
    - name: Install Elasticsearch
      become: true
      ansible.builtin.yum:
        name: "/tmp/elasticsearch-{{ version }}-x86_64.rpm"
        state: present
    - name: Configure Elasticsearch
      become: true
      ansible.builtin.template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: 0755
      notify: restart Elasticsearch

- name: Install Kibana
  hosts: kibana
  handlers:
    - name: restart Kibana
      become: true
      ansible.builtin.service:
        name: kibana
        state: restarted
  tasks:
    - name: "Download Kibana's rpm"
      ansible.builtin.get_url:
        url: "http://10.2.25.120/kibana-{{ version }}-x86_64.rpm"
        dest: "/tmp/kibana-{{ version }}-x86_64.rpm"
        mode: 0755
      register: download_kibana
      until: download_kibana is succeeded
    - name: Install Kibana
      become: true
      ansible.builtin.yum:
        name: "/tmp/kibana-{{ version }}-x86_64.rpm"
        state: present
    - name: Configure Kibana
      become: true
      ansible.builtin.template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: 0755
      notify: restart Kibana

- name: Install filebeat
  hosts: filebeat
  handlers:
    - name: restart filebeat
      become: true
      ansible.builtin.systemd:
        name: filebeat
        state: restarted
        enabled: true
  tasks:
    - name: "Download filebeat rpm"
      ansible.builtin.get_url:
        url: "http://10.2.25.120/filebeat-{{ version }}-x86_64.rpm"
        dest: "/tmp/filebeat-{{ version }}-x86_64.rpm"
        mode: 0755
      register: download_filebeat
      until: download_filebeat is succeeded
    - name: Install filebeat
      become: true
      ansible.builtin.yum:
        name: "/tmp/filebeat-{{ version }}-x86_64.rpm"
        state: present
      notify: restart filebeat
    - name: Configure filebeat
      become: true
      ansible.builtin.template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: 0755
      notify: restart filebeat
    - name: filebeat modules
      become: true
      ansible.builtin.command:
        cmd: filebeat modules enable system
        chdir: /usr/share/filebeat/bin
      register: filebeat_modules
      changed_when: filebeat_modules.stdout != 'already enabled'

    - name: Kibana dashboard
      become: true
      ansible.builtin.command:
        cmd: filebeat setup
        chdir: /usr/share/filebeat/bin
      register: filebeat_setup
      changed_when: false
      until: filebeat_setup is succeeded
